name: upi_pay_ind
description: A flutter plugin to launch UPI payment applications on Android and iOS towards making UPI payments.
version: 1.0.1

homepage: https://github.com/sj10bsrinivasan/upi_pay_ind

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^1.2.0
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sj10bsrinivasan.upi_pay_ind
        pluginClass: UpiPayPlugin
      ios:
        pluginClass: UpiPayPlugin
  assets:
    - assets/apps/ios/
